export const EMAIL_CHANGED     = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED  = 'PASSWORD_CHANGED';
export const LOGIN_USER_SUCESS = 'LOGIN_USER_SUCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const LOGIN_USER = 'LOGIN_USER';
